### ISSUE TITLE
Call a function from a Shared Controller while routing

### ISSUE THREAD

**Issue by mvand** [opitzconsulting/jquery-mobile-angular-adapter#145] opened 2013-03-18 15:50 UTC
I didn't understand the behavior of onActivate property while routing.

Here is a part of my code:
when('/conferences/:day', {
                    templateUrl: '#conferences',
                    onActivate: 'setDay(day)',
                    jqmOptions: {transition:'slide'}
                })
And when i navigate to /conferences/2, my function setDay isn't called.
How to make this ?

**Comment by tbosch** [comment] 2013-03-20 18:10
Hi,
Yes, this should work, if your controller adds the `setDay` function to the scope...
Could you provide a jsfiddle?

Tobias

**Comment by tbosch** [comment] 2013-03-22 12:12
Hi,
here is a simple example: http://jsfiddle.net/ZHKBA/123/

Does this help?

Tobias

**Comment by mvand** [comment] 2013-03-25 12:51
Ok so it works with a simple ng-controller.
I tried to combine onActivate with a ngm-shared-controller and that's why onActivate was never called.

Thxs.

**Comment by tbosch** [comment] 2013-03-27 10:32
Hi,
this is also working with a shared controller, see here: http://jsfiddle.net/tigbro/ZHKBA/125/
Please note that with shared controllers you have to add the prefix of the shared controller to the `onActivate` expression.

Closing this as not a bug.
Tobias

**Closed as completed by tbosch** 2013-03-27 10:32 UTC
