### ISSUE TITLE
Checkbox widget not displayed correctly.

### ISSUE THREAD

**Issue by jaumeavila** [opitzconsulting/jquery-mobile-angular-adapter#164] opened 2013-04-09 12:19 UTC
Hi,
When creating a single checkbox, it is not correctly rendered.
You can see it here:
http://jsfiddle.net/s3qKK/

According to the documentation, the widget is created like this
`<label ng-repeat="l in [1,2]">
    {{l}}
    <input type="checkbox">
</label>`

I guess that a name and an id can be inserted and the input element can be closed.
As you can see, it is rendered a vertical bar instead of the regular square.

Thanks,

Jaume

**Comment by tbosch** [comment] 2013-04-10 16:34
Hi,
this bug is not related to the adapter, as it is reproducible with plain jquery mobile: 
http://jsfiddle.net/ZHKBA/130/

However, using jQuery 1.8.1, the bug does not exist:
http://jsfiddle.net/ZHKBA/131/

Tobias

**Comment by tbosch** [comment] 2013-04-10 16:48
jQuery Mobile does officially support jQuery 1.9.1
http://jquerymobile.com/blog/2013/02/20/jquery-mobile-1-3-0-released/   ...

In the latest jQuery Mobile build (not released yet), there is no problem:
http://jsbin.com/uzeloj/1/

Closing this, as not a bug in the adapter.
To summarize the workarounds:
- use jQuery 1.8.x
- wrap the checkbox into a form element.

Tobias

**Closed as completed by tbosch** 2013-04-10 16:48 UTC
