### ISSUE TITLE
Routing fixed in 1.1.2 SNAPSHOT but local html access (i.e. 'file:///....') not working instead. 

### ISSUE THREAD

**Issue by chongtaiyet** [opitzconsulting/jquery-mobile-angular-adapter#72] opened 2012-11-20 16:40 UTC
Hi, I am glad that the angular router start to work in 1.1.2 SNAPSHOT, great job!
My current mobile project require mobile devices to access the html files locally. This work in 1.1.1, tested in iOS and android devices via Titanium Appcelerator as HTML wrapper.
However, local html access fail to work in 1.1.2. My application fail to start. I was able the simulate the same problem in desktop Firefox (i.e. by double clicking the html file in file explorer). I captured the following error message with the help of firebugs:

Error: Invalid url "file:///Users/chongtaiyet/Desktop/nodejs/jqmang/public/index.html", missing path prefix "file:///Users/chongtaiyet/Desktop/nodejs/jqmang/public" !
file:///Users/chongtaiyet/Desktop/nodejs/jqmang/public/framework/angular/script/angular.js Line 4965

Would this means by solving routing issue we had to sacrifice local html file access?

**Comment by Mordred** [comment] 2012-11-21 06:47
Try to add

``` html
<base />
```

to your head tag. http://www.w3schools.com/tags/tag_base.asp

**Comment by chongtaiyet** [comment] 2012-11-21 09:15
Thanks Mordred.  

My application able to run again after placing &lt;base/&gt;. However, the routing does not work unless I append the relative path with ".html":

```
   From
   -------
   $routeProvider.when('/profile', {templateUrl: 'profile.html', jqmOptions: { transition: 'slide' }})


   To
   -------
   $routeProvider.when('/profile.html', {templateUrl: 'profile.html', jqmOptions: { transition: 'slide' }});
```

and inside my app, i have to remove the leading "/" from reference link and append the link with .html instead:

```
  From
  -------
  <a href="/profile" data-role="button">Profile</a>

  To
  -------
  <a href="profile.html" data-role="button">Profile</a>
```

Of course, this is only applicable if we are opening the html file directly. The routing work as per normal if we host the file via web server.

**Comment by tbosch** [comment] 2012-11-21 10:33
Hi,
thanks for reporting. I will also look into this. Is the problem when loading the initial page, or when clicking on a link in that page that loads a sub-page?

Tobias

**Comment by chongtaiyet** [comment] 2012-11-21 10:56
Hi,

The problem occurs when loading the initial page. You can save and executing following html code. 

```
<!DOCTYPE html> 
<html ng-app> 
<head> 
    <title>mSQS</title> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="jquery.mobile-1.2.0.css" />    
    <script type="text/javascript" src="jquery-mobile-angular-adapter-standalone-1.1.2-SNAPSHOT.js"> </script>
 </head> 

      <body> 
      <div data-role="page" id="main">
      <p><a href="/profile" data-role="button" data-transition="slide">Profile</a></p>
      </div>
 </body>
 </html>
```

You will getting the error message I mentioned in my initial post. 

As for the routing, once I place the &lt;base/&gt;, I have to change all the link from "/links" to "link.html"

Tai Yet

**Comment by tbosch** [comment] 2012-12-11 08:51
Hi,
I created an issue for angular, see https://github.com/angular/angular.js/issues/1690
Also, I will include a patch in the adapter so that this is working also before the issue is fixed in angular.

Tobias

**Closed as completed** 2012-12-11 08:52 UTC
